# Start numpy  today 24/12/2022

In [1]:
import numpy as np

In [2]:
myar = np.array([32,21,3,21],np.int16)

In [3]:
myar[1]

21

In [4]:
myarr = np.array([[32,21,3,21]],np.int64)

In [5]:
myarr[0,1]

21

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
 myarr[0,1] = 54

In [9]:
myarr

array([[32, 54,  3, 21]], dtype=int64)

# Array Creation: Conversion from other python structures:

In [10]:
listarray = np.array([[1,2,3],[5,7,9],[54,6,0]])

In [11]:
listarray

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [54,  6,  0]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({23,4,56})

array({56, 4, 23}, dtype=object)

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.size

10

In [19]:
rng=np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1,30,4)

In [22]:
lspace

array([ 1.        , 10.66666667, 20.33333333, 30.        ])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 1.24610383e-306, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 1.29060531e-306, 6.89805151e-307,
        1.78020169e-306, 1.42410974e-306, 2.22507386e-306]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([ 1.        , 10.66666667, 20.33333333, 30.        ])

In [27]:
ide = np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
 arr= arr.ravel()

In [34]:
arr.shape

(99,)

# numpy Axis ok---

In [35]:
x = [[1,2,3],[4,5,6],[7,0,1]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [38]:
ar.sum(axis=0)

array([12,  7, 10])

In [40]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [41]:
ar.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [42]:
ar.shape

(3, 3)

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
0
1


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [48]:
ar.nbytes

36

In [50]:
oneD = np.array([1,32,43,6,65])

In [53]:
oneD.argmax()

4

In [54]:
oneD.argmin()

0

In [55]:
oneD.argsort()

array([0, 3, 1, 2, 4], dtype=int64)

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [57]:
ar.argmin()

7

In [58]:
ar.argmax()

6

In [61]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [62]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [63]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [64]:
 ar.ravel

<function ndarray.ravel>

In [65]:
 ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 0, 1])

In [67]:
ar.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [72]:
ar2 = np.array([[1, 2, 1],
       [6, 0, 3],
       [5, 1, 0]])

In [73]:
ar+ar2

array([[ 2,  4,  4],
       [10,  5,  9],
       [12,  1,  1]])

In [74]:
ar*ar2 

array([[ 1,  4,  3],
       [24,  0, 18],
       [35,  0,  0]])

In [75]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 0.        , 1.        ]])

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [78]:
ar.sum()

29

In [80]:
ar.max()

7

In [81]:
ar.min()

0

In [82]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [83]:
type(np.where(ar>5))

tuple

In [84]:
np.count_nonzero(ar)

8

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

# less size taken by the numpy in array

In [87]:
import sys

In [88]:
py_ar = [0,1,5,34]

In [89]:
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1)*len(py_ar)

112

In [91]:
np_ar.itemsize*np_ar.size

16

In [92]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [93]:
ar.tolist()

[[1, 2, 3], [4, 5, 6], [7, 0, 1]]